### PR TITLE
Flowers dev

### LINKED ISSUE #2: Make into flowers

### PR DESCRIPTION
**Pull request by nonlaminar**
- Created flower lab
- 5 flowers take 33ish seconds on my machine
- Updated directory structure
- Updated README
- Finished Jupyternotebook

### CODE REVIEW

**Comment by nonlaminar** [comment]
also can I rename this repository to P1-Optimization ? it just doesn't make sense that its circles now

**Comment by nonlaminar** [comment]
This branch can be deleted once merged, but the dev_flowers_stars branch has all of the old code for circles, flowers and stars, so I suggest we leave it incase we want to revisit older versions

**Comment by lukefahr** [comment]
> also can I rename this repository to P1-Optimization ? it just doesn't make sense that its circles now

Yes.

**Comment by lukefahr** [comment]
If you think it's good to go, please go ahead and merge.  Can you also work on the assignment writeup?

**Comment by nonlaminar** [comment]
Will do - and yes, docs and autograder shortly

**Pull request merged**
